# Generated by Django 4.1.4 on 2024-04-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UseCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=1000)),
                ("paragraph", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=1000)),
                ("title", models.CharField(max_length=1000)),
                ("subtitle", models.CharField(max_length=1000)),
                ("fields", models.JSONField()),
                ("url", models.CharField(max_length=1000)),
                ("usecases", models.ManyToManyField(to="api.usecases")),
            ],
        ),
    ]
