# Generated by Django 4.1.4 on 2024-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttypes",
            name="name",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
